
export const SocketEvents = {

    JOIN_ROOM: 'JOIN_ROOM',
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    LEAVE_ROOM: 'LEAVE_ROOM',
    JOINED_CHAT: 'JOINED_CHAT',
    LEFT_CHAT: 'LEFT_CHAT',
    SEND_MESSAGE: 'SEND_MESSAGE'
};
